### ISSUE TITLE
HUT:  undefined method `alternative_title' for #FileSet:0x00007faefd9df720

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1133]
### Descriptive summary

This test broke when we upgrade Hyrax from 2.9.8 to 3.6.

undefined method `alternative_title' for #FileSet:0x00007faefd9df720

### Expected behavior

Something about alternate_title being part of required.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by scherztc** [comment]
https://github.com/samvera/hyrax/issues/4318

**Comment by scherztc** [comment]
https://github.com/samvera/hyrax/pull/4354

**Comment by scherztc** [comment]
- [ ] Remove alternate_title from overwrite code.
- [ ] Change alternate_title to alternative_title in Forms, Mappings, Seeds, Allow List, Solr indexing
- [ ] Rake Task to migrate what ever is in alternate_title to alternative_title.
- [ ] Clean Up Database for alternate_title
- [ ] Confirm new works only have alternative_title

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBSCHOLAR-10?atlOrigin=eyJpIjoiZTYzYzk0ZTMwNjAzNDA0ZDhiNjE0NTU3NjUyOTIzYzEiLCJwIjoiaiJ9
